version: "3.9"

services:

  server: # hostname
    image: altec3/testwork
    restart: always
    env_file:
      - ./.env
    ports:
      - 80:8000
    depends_on:
      psql:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    command: python manage.py runserver 0.0.0.0:8000

  migrations: # hostname
    image: altec3/testwork
    depends_on:
      psql:
        condition: service_healthy
    command: python manage.py migrate

  psql: # hostname
    image: postgres:15.0-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    volumes:
      - ./psql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  psql_data:
